{% set name = "filelock" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
   sha256: b3ad481724adfb2280773edd95ce501e497e88fa4489c6e41e637ab3fd9a456c

build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - filelock

about:
  home: https://github.com/benediktschmitt/py-filelock
  license: Public Domain
  summary: 'A platform independent file lock.'
