{% set name = "pandas" %}
{% set version = "0.23.3" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 9cd3614b4e31a0889388ff1bd19ae857ad52658b33f776065793c293a29cf612

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
        - cython
        - numpy 1.11.*
    run:
        - python
        - numpy >=1.11
        - python-dateutil
        - pytz

test:
    imports:
        - pandas

about:
    home: http://pandas.pydata.org
    license: BSD 3-clause
    summary: high-performance, easy-to-use data structures and data analysis tools.
