{% set version = "4.7.0" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  fn: ipykernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: 354986612a38f0555c43d5af2425e2a67506b63b313a0325e38904003b9d977b

build:
  number: 0
  script:
    - pip install --no-deps .
    - python -m ipykernel install --prefix $PREFIX

requirements:
  build:
    - pip
    - python
    - jupyter_client
    - ipython >=4.0
    - tornado >=4.0
  run:
    - python
    - ipython >=4.0
    - traitlets
    - jupyter_client
    - tornado >=4.0

test:
  imports:
    - ipykernel

about:
  home: http://ipython.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
